# Generated by Django 5.2.4 on 2025-07-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_summaryfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='news_audio/'),
        ),
    ]
