# Generated by Django 5.2.4 on 2025-07-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_article_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='categories',
            field=models.ManyToManyField(related_name='user_pref_categories', to='news.category'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_categories',
            field=models.ManyToManyField(related_name='user_pref_preferred', to='news.category'),
        ),
    ]
