# Generated by Django 5.2.4 on 2025-08-05 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_userpreference_categories_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
